export const EXAM = [
  {
    id: 1,
    title: "Thi thử JLPT 01",
    time: 120,
    contest: 7,
    question: 200,
    type: "N1",
  },
  {
    id: 2,
    title: "Thi thử JLPT 02",
    time: 120,
    contest: 7,
    question: 200,
    type: "N1",
  },
  {
    id: 3,
    title: "Thi thử JLPT 03",
    time: 120,
    contest: 7,
    question: 200,
    type: "N1",
  },
  {
    id: 4,
    title: "Thi thử JLPT 04",
    time: 120,
    contest: 7,
    question: 200,
    type: "N1",
  },
  {
    id: 5,
    title: "Thi thử JLPT 05",
    time: 120,
    contest: 7,
    question: 200,
    type: "N1",
  },
  {
    id: 6,
    title: "Thi thử JLPT 01",
    time: 120,
    contest: 7,
    question: 200,
    type: "N2",
  },
  {
    id: 7,
    title: "Thi thử JLPT 02",
    time: 120,
    contest: 7,
    question: 200,
    type: "N2",
  },
  {
    id: 8,
    title: "Thi thử JLPT 03",
    time: 120,
    contest: 7,
    question: 200,
    type: "N2",
  },
  {
    id: 9,
    title: "Thi thử JLPT 04",
    time: 120,
    contest: 7,
    question: 200,
    type: "N2",
  },
  {
    id: 10,
    title: "Thi thử JLPT 05",
    time: 120,
    contest: 7,
    question: 200,
    type: "N2",
  },
  {
    id: 11,
    title: "Thi thử JLPT 01",
    time: 120,
    contest: 7,
    question: 200,
    type: "N3",
  },
  {
    id: 12,
    title: "Thi thử JLPT 02",
    time: 120,
    contest: 7,
    question: 200,
    type: "N3",
  },
  {
    id: 13,
    title: "Thi thử JLPT 03",
    time: 120,
    contest: 7,
    question: 200,
    type: "N3",
  },
  {
    id: 14,
    title: "Thi thử JLPT 04",
    time: 120,
    contest: 7,
    question: 200,
    type: "N3",
  },
  {
    id: 15,
    title: "Thi thử JLPT 05",
    time: 120,
    contest: 7,
    question: 200,
    type: "N3",
  },
  {
    id: 16,
    title: "Thi thử JLPT 06",
    time: 120,
    contest: 7,
    question: 200,
    type: "N2",
  },
  {
    id: 17,
    title: "Thi thử JLPT 01",
    time: 120,
    contest: 7,
    question: 200,
    type: "N4",
  },
  {
    id: 18,
    title: "Thi thử JLPT 02",
    time: 120,
    contest: 7,
    question: 200,
    type: "N4",
  },
  {
    id: 19,
    title: "Thi thử JLPT 03",
    time: 120,
    contest: 7,
    question: 200,
    type: "N4",
  },
  {
    id: 20,
    title: "Thi thử JLPT 04",
    time: 120,
    contest: 7,
    question: 200,
    type: "N4",
  },
  {
    id: 21,
    title: "Thi thử JLPT 05",
    time: 120,
    contest: 7,
    question: 200,
    type: "N4",
  },
  {
    id: 22,
    title: "Thi thử JLPT 01",
    time: 120,
    contest: 7,
    question: 200,
    type: "N5",
  },
  {
    id: 23,
    title: "Thi thử JLPT 02",
    time: 120,
    contest: 7,
    question: 200,
    type: "N5",
  },
  {
    id: 24,
    title: "Thi thử JLPT 03",
    time: 120,
    contest: 7,
    question: 200,
    type: "N5",
  },
  {
    id: 25,
    title: "Thi thử JLPT 04",
    time: 120,
    contest: 7,
    question: 200,
    type: "N5",
  },
  {
    id: 26,
    title: "Thi thử JLPT 05",
    time: 120,
    contest: 7,
    question: 200,
    type: "N5",
  },
  {
    id: 27,
    title: "Thi thử JLPT 06",
    time: 120,
    contest: 7,
    question: 200,
    type: "N5",
  },
];
