// export const EXAM = [
//   {
//     title: "Đề thi 01",
//     time: 120,
//     contest: 7,
//     question: 200,
//     type: "N1",
//   },
//   {
//     title: "Đề thi 02",
//     time: 120,
//     contest: 7,
//     question: 200,
//     type: "N1",
//   },
//   {
//     title: "Đề thi 03",
//     time: 120,
//     contest: 7,
//     question: 200,
//     type: "N1",
//   },
//   {
//     title: "Đề thi 04",
//     time: 120,
//     contest: 7,
//     question: 200,
//     type: "N1",
//   },
//   {
//     title: "Đề thi 05",
//     time: 120,
//     contest: 7,
//     question: 200,
//     type: "N1",
//   },
//   {
//     title: "Đề thi 01",
//     time: 120,
//     contest: 7,
//     question: 200,
//     type: "N2",
//   },
//   {
//     title: "Đề thi 02",
//     time: 120,
//     contest: 7,
//     question: 200,
//     type: "N2",
//   },
//   {
//     title: "Đề thi 03",
//     time: 120,
//     contest: 7,
//     question: 200,
//     type: "N2",
//   },
//   {
//     title: "Đề thi 04",
//     time: 120,
//     contest: 7,
//     question: 200,
//     type: "N2",
//   },
//   {
//     title: "Đề thi 05",
//     time: 120,
//     contest: 7,
//     question: 200,
//     type: "N2",
//   },
//   {
//     title: "Đề thi 01",
//     time: 120,
//     contest: 7,
//     question: 200,
//     type: "N3",
//   },
//   {
//     title: "Đề thi 02",
//     time: 120,
//     contest: 7,
//     question: 200,
//     type: "N3",
//   },
//   {
//     title: "Đề thi 03",
//     time: 120,
//     contest: 7,
//     question: 200,
//     type: "N3",
//   },
//   {
//     title: "Đề thi 04",
//     time: 120,
//     contest: 7,
//     question: 200,
//     type: "N3",
//   },
//   {
//     title: "Đề thi 05",
//     time: 120,
//     contest: 7,
//     question: 200,
//     type: "N3",
//   },
//   {
//     title: "Đề thi 06",
//     time: 120,
//     contest: 7,
//     question: 200,
//     type: "N2",
//   },
//   {
//     title: "Đề thi 01",
//     time: 120,
//     contest: 7,
//     question: 200,
//     type: "N4",
//   },
//   {
//     title: "Đề thi 02",
//     time: 120,
//     contest: 7,
//     question: 200,
//     type: "N4",
//   },
//   {
//     title: "Đề thi 03",
//     time: 120,
//     contest: 7,
//     question: 200,
//     type: "N4",
//   },
//   {
//     title: "Đề thi 04",
//     time: 120,
//     contest: 7,
//     question: 200,
//     type: "N4",
//   },
//   {
//     title: "Đề thi 05",
//     time: 120,
//     contest: 7,
//     question: 200,
//     type: "N4",
//   },
//   {
//     title: "Đề thi 01",
//     time: 120,
//     contest: 7,
//     question: 200,
//     type: "N5",
//   },
//   {
//     title: "Đề thi 02",
//     time: 120,
//     contest: 7,
//     question: 200,
//     type: "N5",
//   },
//   {
//     title: "Đề thi 03",
//     time: 120,
//     contest: 7,
//     question: 200,
//     type: "N5",
//   },
//   {
//     title: "Đề thi 04",
//     time: 120,
//     contest: 7,
//     question: 200,
//     type: "N5",
//   },
//   {
//     title: "Đề thi 05",
//     time: 120,
//     contest: 7,
//     question: 200,
//     type: "N5",
//   },
//   {
//     title: "Đề thi 06",
//     time: 120,
//     contest: 7,
//     question: 200,
//     type: "N5",
//   },
// ];

// export const CONTEST = [
//   {
//     name: "Tất cả",
//   },
//   {
//     name: "N1",
//   },
//   {
//     name: "N2",
//   },
//   {
//     name: "N3",
//   },
//   {
//     name: "N4",
//   },
//   {
//     name: "N5",
//   },
// ];
